# Generated by Django 5.1.1 on 2024-09-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
